# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://Skyller13.github.io"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Gaetan Barriol"
title: "{ Gaetan Barriol }"
description: "Blog and website of Gaetan Barriol, blogging mainly for tech. Opinions expressed are mine."
keywords: "gaetan, barriol, personal"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
################
# Header layout#
################
background-img: "img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "What are you waiting for?"
# me-img: "/img/author.jpg"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/Skyller13.png?size=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "Gaetan"

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "gaetan.barriol@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "Gaetan Barriol is an awesome person. He lives in Montréal, where he works on engineering projects. 
  In his spare time, Gaetan likes to eat food, to hit the gym and to play games."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/Skyller13"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/gaetan-barriol/"
  - icon: "youtube"
    url: "https://www.youtube.com/@gbarriol"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
