# Site settings
url: "https://Skyller13.github.io"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############
lang: "en"
author: "Gaetan Barriol"
title: "{ Gaetan Barriol }"
description: "Blog and website of Gaetan Barriol. Here you can find portofolio and information about myself."
keywords: "gaetan, barriol, personal, programming, game, development, developer, engine, tools, gameplay"

################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################
quote: "Building experiences, one line of code at a time."
me-img: "https://github.com/Skyller13.png?size=500"

############
# Timeline #
############
events:
  - image: "/img/timeline/dpt.png"
    date: "May 2022 - Today"
    description: "Programming software applications"
  - image: "/img/timeline/IvoryTower.png"
    date: "July 2021 - December 2021"
    description: "UI Programmer trainee"
  - image: "/img/timeline/creajeux.png"
    date: "September 2017 - July 2021 "
    description: "Started coding -<br>Bachelor in programming"
  - image: "/img/timeline/logo-saint-eloi.png"
    date: "September 2015 - July 2017"
    description: "BTEC in electronics"
  - image: "/img/timeline/young_me.jpg"
    description: "A younger version of me ready to overcome challenges!"
    
############
# PROJECTS #
############
projects:
  - title: "Europe Madness"
    image: "img/projects/EuropeMadness.png"
    overview: "2D - Lua - TowerDefense"
    description: "Europe Madness is a tower defense that takes place during WW1. 
    In this game, you have to defeat waves of enemies by placing and upgrading units. 
    I worked on the user interface and the gameplay core mechanics."
    link: "https://drive.google.com/file/d/1VVd0pPadSf2CuZr5N5XMRIZEnGUL5kYA/view?usp=sharing"
  - title: "inSECURE"
    image: "img/projects/inSecure.png"
    overview: "2D - C - Reflexion/ Shooter"
    gif: "img/projects/inSecure.gif"
    description: "In inSECURE, you play an investigator and a former soldier who try to solve the mystery of a series of child abductions in a dystopian world.
    I worked on the user interface and the gameplay core mechanics"
    link: "https://drive.google.com/file/d/1QSvtCIzH1PI-rpZOaKuJoasIuoDErI9F/view?usp=sharing"
    trailer: "https://isaacmontagne.fr/assets/video/insecure/trailer.webm"
  - title: "Stack"
    image: "img/projects/Stack.png"
    overview: "3D - C# - Unity"
    description: "A reproduction of the famous game with the same name. Done in half a day."
    link: "https://drive.google.com/file/d/1wr3TpIR26ddP3Xh8mblkqAfpq_uPIheJ/view?usp=sharing"
  - title: "Unexpected Heroes"
    image: "img/projects/UnexpectedHeroes.png"
    overview: "3D - C# - Dungeon Crawler"
    description: "In Unexpected Heroes, you play as a monster who is willing to do anything to become the hero of his story. 
    I mainly worked on the gameplay, menus, interfaces and systems of the game."
    link: "https://drive.google.com/file/d/1ljAXDTp-LPRrKzM38IztLmB8YHYgeAGx/view?usp=sharing"
    trailer: "https://www.youtube.com/watch?v=mEeoPgjucDE"
  - title: "Le monde de Kira"
    image: "img/projects/Kira.png"
    overview: "3D - C++ - Action-RPG"
    description: "In The World of Kira, play as Kira, a young kitten who has just been adopted and who imagines living an epic life in his new home.
    In this game, I developed quests and dialogue systems and contributed to the creation of the user interface and gameplay."
    link: "https://drive.google.com/file/d/1My0QhxEWNsSW_ZLTI7_k6i-zMhXoe43D/view?usp=sharing"
    trailer: "https://www.youtube.com/watch?v=ZLhrw5ovMwM"
  - title: "The Crew 2 (Live)"
    alt_image: "img/projects/TC2_logo.png"
    image: "img/projects/TheCrew2.png"
    overview: "3D - C++ - Arcade-Racing"
    description: "The Crew 2 is an arcade racing video game developed by Ivory Tower and published by Ubisoft.
    I worked as a trainee UI programmer and mainly contributed to the creation of a new menu for one of the game updates."
    trailer: "https://www.youtube.com/watch?v=7Dj6M85WCm8"
  - title: "Renamer"
    image: "img/projects/Tools.png"
    overview: "Tools - Batch"
    description: "This little script is a batch script for renaming files in a given folder. Using a prompt and a path given by the user, 
    it iterates through all files in the specified folder and renames each file, appending an incrementing counter and keeping the original file extension."
    link: "https://drive.google.com/file/d/1trvxl7JZXpMdI21mED94GxNTgQ0Zx1Wd/view?usp=sharing"
  - title: "Renamer v2"
    image: "img/projects/Tools.png"
    overview: "Tools - Batch"
    description: "This second version of this script is a batch script designed for renaming files in order, but this time it adds a prefix to the beginning of each file's name."
    link: "https://drive.google.com/file/d/1YNIwSxTuVZ_0A6HAiZ9Mo1ddhMhRkGJx/view?usp=sharing"
  - title: "Okawari"
    image: "img/projects/Okawari.png"
    overview: "3D - C# - VR"
    description: "Four users are invited to sit at one of the tables in the Okawari restaurant to discover a wide variety of dishes and drinks from the Japanese izakaya gastronomy.
    I mainly worked on content integration, developed some gameplay mechanics and set up UI."
    link: "https://www.labiennale.org/en/cinema/2022/venice-immersive/okawari"
  - title: "Seeing Loud : Basquiat and Music"
    image: "img/projects/Basquiat.png"
    overview: "2D - C# - AR"
    description: "Basquiat and Music app features interactive content that transports the visitor into New York of the 1970s and 1980s, thus amplifying their experience of the exhibition.
    I mainly worked on the UI systems, the integration of content and developed some systems to enhance the user experience."
    link: "https://www.mbam.qc.ca/fr/expositions/jean-michel-basquiat/"
    trailer: "https://www.youtube.com/watch?v=toRe8_Zontk"
  - title: "Daisy Engine"
    image: "img/projects/Tools.png"
    overview: "3D - C++ - Vulkan engine"
    description: "This personal project is a little 3D game engine used to learn Vulkan with the usage C++."
    link: "https://github.com/Skyller13/DaisyEngine"
  - title: "Nerisia"
    image: "img/projects/Nerisia.png"
    overview: "Design - Tabletop RPG"
    description: "Nerisia is a tabletop game that I am designing, inspired by the iconic Dungeons & Dragons but also by many video games such as Skyrim, The Witcher, Kingdom of Amalur : Reckoning."
  - title: "Spread"
    image: "img/projects/Game.png"
    overview: "3D - C# - Top-Down Shooter"
    description: "Spread is a 3D game that I am working on where you play in a post-apocalyptic world where each character is mortal and has it's very own quests.
    Inspired by many zombie games such as Dying Light, Dead Island and World War Z."

##########
# Skills #
##########
soft_skills:
  - name: Problem-Solving
    description: "Debugging, optimization, and tackling complex technical challenges."
    icon: "img/skills/problem_solving.png"
  - name: Teamwork
    description: "Working effectively with designers, artists, and fellow developers."
    icon: "img/skills/teamwork.png"
  - name: Communication
    description: "Writing documentation, explaining concepts, and giving technical presentations."
    icon: "img/skills/communication.png"
  - name: Project Management
    description: "Experience with Agile, Scrum, and Kanban methodologies."
    icon: "img/skills/project_management.png"
  - name: Time Management
    description: "Balancing multiple projects and meeting deadlines efficiently."
    icon: "img/skills/time_management.png"
  - name: Innovation
    description: "Developing unique mechanics, tools, and technical solutions."
    icon: "img/skills/creativity_innovation.png"
    
game_engines:
  - name: Unity
    icon: "img/skills/unity.png"
  - name: Unreal Engine
    icon: "img/skills/unreal.png"

project_management:
  - name: Jira
    icon: "img/skills/jira.png"
  - name: Trello
    icon: "img/skills/trello.png"
  - name: Miro
    icon: "img/skills/miro.png"
  - name: Confluence
    icon: "img/skills/confluence.png"

version_control:
  - name: GitHub
    icon: "img/skills/github.png"
  - name: SourceTree
    icon: "img/skills/sourcetree.png"
  - name: Perforce
    icon: "img/skills/perforce.png"
  - name: Tortoise SVN
    icon: "img/skills/svn.png"

graphics_apis_libraries:
  - name: Vulkan
    icon: "img/skills/vulkan.png"
  - name: OpenGL
    icon: "img/skills/opengl.png"
  - name: SFML
    icon: "img/skills/sfml.png"
  - name: OpenCV
    icon: "img/skills/opencv.png"
  - name: ImGui
    icon: "img/skills/imgui.png"

programming_languages:
  - name: C
    icon: "img/skills/c.png"
  - name: C#
    icon: "img/skills/csharp.png"
  - name: C++
    icon: "img/skills/cplusplus.png"
  - name: Lua
    icon: "img/skills/lua.png"
  - name: AS3
    icon: "img/skills/as3.png"

###########
# Contact #
###########
email: "gaetan.barriol@gmail.com"
phone: "+1 579-421-6389"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/Skyller13"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/gaetan-barriol/"
  - icon: "youtube"
    url: "https://www.youtube.com/@gbarriol"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Timeline: "timeline"
  Projects: "projects"
  Skills: "skills"
  Contact: "contact"
  
include:
  - assets
  
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml

# Enable minification SASS
sass:
  style: compressed
plugins:
   - jekyll-spaceship
