# Site settings
url: "https://Skyller13.github.io"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############
lang: "en"
author: "Gaetan Barriol"
title: "{ Gaetan Barriol }"
description: "Blog and website of Gaetan Barriol. Here you can find portofolio and information about myself."
keywords: "gaetan, barriol, personal, programming, game, development, developer, engine, tools, gameplay"

################
# Header layout#
################
background-img: "img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################
quote: "What are you waiting for?"
me-img: "https://github.com/Skyller13.png?size=500"

############
# Timeline #
############
events:
  - image: "/img/timeline/dpt.png"
    date: "May 2022 - Today"
    description: "Programming software applications"
  - image: "/img/timeline/IvoryTower.png"
    date: "July 2021 - December 2021"
    description: "UI Programmer trainee"
  - image: "/img/timeline/creajeux.png"
    date: "September 2017 - July 2021 "
    description: "Started coding -<br>Bachelor in programming"
  - image: "/img/timeline/logo-saint-eloi.png"
    date: "September 2015 - July 2017"
    description: "BTEC in electronics"
    
# First image of the Timeline
timeline-img: "/img/timeline/young_me.jpg"

###########
# Contact #
###########
email: "gaetan.barriol@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/Skyller13"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/gaetan-barriol/"
  - icon: "youtube"
    url: "https://www.youtube.com/@gbarriol"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Timeline: "timeline"
  Projects: "projects"
  Contact: "contact"
  
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml

# Enable minification SASS
sass:
  style: compressed
plugins:
   - jekyll-spaceship
